### ISSUE TITLE
Update generator to change pillar include structure

### ISSUE THREAD

**Issue by mshade** [forumone/generator-web-starter-salt#1]
Pillars were not getting merged the way we expected, whether due to bug or misunderstanding. This has been fixed in salt branch of web starter, change here: https://github.com/forumone/web-starter/commit/10d0eca1ca1a8c1246300a299f17bfcbe347771a

Please merge this in (perhaps also see what has changed from salt branch since the generator created?) and put up new NPM package of the salt generator

**Comment by TrevorScheitrum** [comment]
this is manually merged into generator-webstarter-salt via commit 
https://github.com/forumone/generator-web-starter-salt/commit/cba6dfa1972ba623d2144b52d9d9c5d23396856d
